---
- name: App - Config File
  action: template owner=sense group=sense mode=644 src=../templates/{{ app }}/config.json.j2 dest="/home/app/sense/{{ app }}/builds/{{ appbuildinfo.name }}-{{ appbuildinfo.version }}-{{ appbuildinfo.branch | replace('/','_') }}-{{ appbuildinfo.build }}/config.json"
