---
#Clean builds - copy script to /root/bin
- name: Clean builds - make sure /root/bin exists
  action: file state=directory path=/root/bin owner=root group=root mode=750

- name: Clean builds - copy script to /root/bin
  action: copy owner=root mode=755 src=../files/{{ item }} dest={{ item }} backup=yes
  with_items:
    - /root/bin/clean-up-builds.sh

#- name: Clean Builds - Run script
- name: Clean Builds - Run script
  action: shell /root/bin/clean-up-builds.sh {{ app }} 
