---
- name: App - Clear download directory
  file: 
    state: absent
    path: /home/app/sense/{{ app }}/tmp

- debug:
    var: lookup('vars', 'dev_' + appshort)

- name: App - Create download directory
  file:
    state: directory
    path: /home/app/sense/{{ app }}/tmp

- debug:
    msg: "/home/app/sense/{{ app }}/download/{{ filename }}"

- name: App - Unzip
  unarchive:
    src: /home/app/sense/{{ app }}/download/{{ filename }}
    dest: /home/app/sense/{{ app }}/tmp/
    copy: no
