---
- name: DMC - check if settings file exists in current/etc
  stat:
    path: /home/app/sense/ednl-software-delta-maker-client/current/etc/settings
  register: settingsfile

- name: DMC - Copy previous settings file(if it exsists)
  copy:
    src: /home/app/sense/ednl-software-delta-maker-client/current/etc/settings
    dest: /home/app/sense/ednl-software-delta-maker-client/tmp/etc/settings
  when:
    - settingsfile.stat.exists == true
