---
# Hardware tester - install required packages
- name: Hardware tester - install required packages
  action: command pacman -Sy --noconfirm {{ item }}
  with_items:
    - i2c-tools
    - alsa-tools
    - alsa-utils
    - dtc-overlay
    - screen
    - evtest
  when: (ansible_facts.machine == "armv7l" and firstrun == 1)
