##
# App ednl-software-delta-maker-client
#
---
- hosts: localbbb
  remote_user: root
  become: true

  tags:
    - devupdate
    - devupdate-dmc

  vars_files:
    - ../vars/ednl-software-delta-maker-client.yml

  handlers:
    - include_tasks: ../handlers/exarun.yml

  tasks:
#    - include_tasks: ../tasks/app-startupdate.yml #disabled until properly functioning
    - include_tasks: ../tasks/exarun.yml
    - include_tasks: ../tasks/app-unzip.yml
    - include_tasks: ../tasks/dmc-activatesettings.yml
    - include_tasks: ../tasks/app-readbuildinfo.yml
    - include_tasks: ../tasks/app-readpackageinfo.yml
    - include_tasks: ../tasks/app-install.yml
    - include_tasks: ../tasks/tools-activate.yml
    - include_tasks: ../tasks/app-cleanup.yml
    - include_tasks: ../tasks/exarun.yml
#    - include_tasks: ../tasks/app-stopupdate.yml #disabled until properly functioning
    - include_tasks: ../tasks/app-startself.yml
