##
# App ednl-sense-module-serial-proxy
#
---
- hosts: localbbb
  remote_user: root
  become: true

  tags:
    - devupdate
    - devupdate-smsp

  vars_files:
    - ../vars/ednl-sense-module-serial-proxy.yml

  tasks:
    - include_tasks: ../tasks/app-unzip.yml
    - include_tasks: ../tasks/app-readbuildinfo.yml
    - include_tasks: ../tasks/app-readpackageinfo.yml
    - include_tasks: ../tasks/app-install.yml
    - include_tasks: ../tasks/tools-activate.yml
    - include_tasks: ../tasks/app-cleanup.yml
