##
# App ednl-sense-module-portal
#
---
- hosts: localbbb
  remote_user: root
  become: true

  tags:
    - devupdate
    - devupdate-smp

  vars_files:
    - ../vars/ednl-sense-module-portal.yml

  tasks:
    - include_tasks: ../tasks/app-unzip.yml
    - include_tasks: ../tasks/app-readbuildinfo.yml
    - include_tasks: ../tasks/app-install.yml
    - include_tasks: ../tasks/app-config.yml
    - include_tasks: ../tasks/sense-symlink.yml
    - include_tasks: ../tasks/app-cleanup.yml
