##
# App ednl-sense-module-portalserver
#
---
- hosts: localbbb
  remote_user: root
  become: true

  tags:
    - devupdate
    - devupdate-smps

  vars_files:
    - ../vars/ednl-sense-module-portalserver.yml

  tasks:
    - include_tasks: ../tasks/exarun.yml
    - include_tasks: ../tasks/app-unzip.yml
    - include_tasks: ../tasks/app-readbuildinfo.yml
    - include_tasks: ../tasks/app-readpackageinfo.yml
    - include_tasks: ../tasks/app-install.yml
    - include_tasks: ../tasks/app-config.yml
    - include_tasks: ../tasks/app-activate.yml
    - include_tasks: ../tasks/app-cleanup.yml